apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: graphql
  namespace: argocd

spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
    
  project: default
  source:
    repoURL: https://github.com/amadouth6/swh-apps.git
    targetRevision: HEAD
    path: apps:/swh-graphql/

 
  syncPolicy:
    syncOptions:
      - CreateNamespace=true    
    
    automated:
      selfHeal: true
      prune: true