#!/usr/bin/env python3

# Copyright (C) 2022  The Software Heritage developers
# See the AUTHORS file at the top-level directory of this distribution
# License: GNU General Public License v3 or later
# See top-level LICENSE file for more information

from common import APPS_DIR


def list_apps():
    """List all the known apps with a requirements.txt file"""
    for req_file in sorted(APPS_DIR.glob("*/requirements.txt")):
        yield req_file.parent.stem


if __name__ == "__main__":
    for app in list_apps():
        print(app)
